/*
 * Pack resources to binary file. Each resource is stored as a base64-encoded
 * string constant
 *
 * input ini file (default "resources.conf", change with -f <name> )
 * has a number of section
 * each section has a number of <name> = <file> pairs
 * files are located relatively to . (change with -d <name>)
 *
 * create output (default "resources" (h,cc), change with -o <name> ) files
 * for each section there is an euqally named namespace
 * for each <name> = <file> pair there is a function std::string <name>() that
 * decodes and returns the string
 *
 */
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <sstream>
#include <unordered_map>

#include "INIReader.h"
#include "base64.h"

using namespace std;

int main(int argc, char **argv) {
  string ini = "resources.conf";
  string out = "resources";
  string dir = ".";

  for (int i = 1; i < argc; i++)
    if (!strcmp(argv[i], "-f")) {
      ini = string(argv[++i]);
    } else if (!strcmp(argv[i], "-o")) {
      out = string(argv[++i]);
    } else if (!strcmp(argv[i], "-d")) {
      dir = string(argv[++i]);
    }

  INIReader reader(ini);
  if (reader.ParseError() < 0) {
    cerr << "cannot parse config file: " << ini << endl;
    exit(1);
  }

  stringstream name;
  name << out << ".h";
  fstream f(name.str(), fstream::out);
  f << "#ifndef ___RESOURCES___" << endl;
  f << "#define ___RESOURCES___" << endl << endl;
  f << "// file generated by " << argv[0] << " from " << ini << endl << endl;
  f << "#include <string>" << endl;
  f << "#include \"base64.h\"" << endl << endl;

  for (auto section : reader.GetSections()) {
    f << "namespace " << section << " {" << endl;
    for (auto field : reader.GetFields(section)) {
      f << "  std::string " << field << "();" << endl;
    }
    f << "};" << endl << endl;
  }
  f << "#endif" << endl;
  f.close();

  name.str("");
  name << out << ".cc";

  f.open(name.str(), fstream::out);
  f << "// file generated by " << argv[0] << " from " << ini << endl << endl;
  f << "#include \"resources.h\"" << endl << endl;

  for (auto section : reader.GetSections()) {
    f << "namespace " << section << " {" << endl;
    unordered_map<string, string> fields;
    for (auto field : reader.GetFields(section)) {
      stringstream ss;
      ss << dir << "/" << reader.Get(section, field, "");
      FILE *rf;
      char *buffer;
      long numbytes;
      if (!(rf = fopen(ss.str().data(), "r"))) continue;
      fseek(rf, 0L, SEEK_END);
      numbytes = ftell(rf);
      fseek(rf, 0L, SEEK_SET);
      buffer = (char *)calloc(numbytes, sizeof(char));
      fread(buffer, sizeof(char), numbytes, rf);
      fclose(rf);
      fields[field] = Base64::Encode(buffer, numbytes);
      free(buffer);
    }
    for (auto field : fields) {
      f << "  std::string " << field.first << "() {  " << endl;
      f << "      std::string ret; " << endl;
      f << "      Base64::Decode(\"" << field.second << "\","
        << field.second.size() << ", ret);" << endl;
      f << "      return ret; " << endl;
      f << "  } " << endl;
    }
    f << "};" << endl << endl;
  }
  f.close();
}
